name: epifeat
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - python=3.12.1
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - anyio==4.2.0
    - appnope==0.1.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - bokeh==3.3.4
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorcet==3.0.1
    - comm==0.2.1
    - contourpy==1.2.0
    - cycler==0.12.1
    - dask==2024.2.0
    - datashader==0.16.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - fonttools==4.49.0
    - fqdn==1.5.1
    - fsspec==2024.2.0
    - h11==0.14.0
    - holoviews==1.18.3
    - httpcore==1.0.2
    - httpx==0.26.0
    - idna==3.6
    - imageio==2.34.0
    - importlib-metadata==7.0.1
    - ipykernel==6.29.1
    - ipython==8.21.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.0
    - jupyter-console==6.6.3
    - jupyter-core==5.7.1
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.2
    - jupyter-server==2.12.5
    - jupyter-server-terminals==0.5.2
    - jupyterlab==4.1.0
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.2
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - linkify-it-py==2.0.3
    - llvmlite==0.42.0
    - locket==1.0.0
    - markdown==3.5.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.4.0
    - mdurl==0.1.2
    - mistune==3.0.2
    - multipledispatch==1.0.0
    - nbclient==0.9.0
    - nbconvert==7.15.0
    - nbformat==5.9.2
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - nibabel==5.2.0
    - notebook==7.0.7
    - notebook-shim==0.2.3
    - numba==0.59.0
    - numpy==1.26.4
    - overrides==7.7.0
    - packaging==23.2
    - pandas==2.2.0
    - pandocfilters==1.5.1
    - panel==1.3.8
    - param==2.0.2
    - parso==0.8.3
    - partd==1.4.1
    - pexpect==4.9.0
    - pillow==10.2.0
    - pip==23.3.1
    - platformdirs==4.2.0
    - plotly==5.19.0
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.43
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pyct==0.5.0
    - pygments==2.17.2
    - pynndescent==0.5.11
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyviz-comms==3.0.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - referencing==0.33.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.17.1
    - scikit-image==0.22.0
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - seaborn==0.13.2
    - send2trash==1.8.2
    - setuptools==68.2.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.6.3
    - tenacity==8.2.3
    - terminado==0.18.0
    - threadpoolctl==3.3.0
    - tifffile==2024.2.12
    - tinycss2==1.2.1
    - toolz==0.12.1
    - tornado==6.4
    - tqdm==4.66.2
    - traitlets==5.14.1
    - types-python-dateutil==2.8.19.20240106
    - typing-extensions==4.9.0
    - tzdata==2023.4
    - uc-micro-py==1.0.3
    - umap-learn==0.5.5
    - uri-template==1.3.0
    - urllib3==2.2.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - wheel==0.41.2
    - widgetsnbextension==4.0.9
    - xarray==2024.2.0
    - xyzservices==2023.10.1
    - zipp==3.17.0
